build:
  - npm ci
  - npm run build

run:
  command: node -e "require('http').createServer((req, res) => require('fs').readFileSync('./dist/index.html', 'utf-8').replace(/\/assets\/([^'\"]+)/g, '/assets/$1'), (req, res) => res.end()).listen(3000)"
